# Generated by Django 6.1 on 2026-08-15 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('package_name_at_booking', models.CharField(max_length=100)),
                ('package_price_at_booking', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addons_total_at_booking', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('service_address_street', models.CharField(max_length=255)),
                ('service_address_suburb', models.CharField(max_length=100)),
                ('service_address_postcode', models.CharField(max_length=10)),
                ('service_address_state', models.CharField(max_length=50)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('approximate_area', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('included_services', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.addonservice')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons', to='bookings.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.cleaningpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.timeslot'),
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='bookings_bl_date_538f03_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='bookings_bo_booking_b730a0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_email'], name='bookings_bo_custome_f6e328_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference'], name='bookings_bo_referen_881a91_idx'),
        ),
    ]
