# Generated by Django 6.1 on 2026-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addons/'),
        ),
    ]
