# Generated by Django 6.1 on 2026-08-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_addonservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed base fee for all bookings.', max_digits=8)),
                ('bedroom_price', models.DecimalField(decimal_places=2, default=49.0, max_digits=8)),
                ('bathroom_price', models.DecimalField(decimal_places=2, default=30.0, max_digits=8)),
                ('living_area_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='base_clean_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='living_areas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.cleaningpackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_name_at_booking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_price_at_booking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
