# Generated by Django 6.1 on 2026-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_pricingconfig_booking_base_clean_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balconies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='balcony_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
        ),
    ]
