# Generated by Django 6.1 on 2026-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_balconies_pricingconfig_balcony_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningpackage',
            name='balconies',
            field=models.IntegerField(default=0, help_text='Number of balconies'),
        ),
        migrations.AddField(
            model_name='cleaningpackage',
            name='bathrooms',
            field=models.IntegerField(default=1, help_text='Number of bathrooms'),
        ),
        migrations.AddField(
            model_name='cleaningpackage',
            name='bedrooms',
            field=models.IntegerField(default=1, help_text='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='cleaningpackage',
            name='living_areas',
            field=models.IntegerField(default=1, help_text='Number of living areas'),
        ),
        migrations.AlterField(
            model_name='cleaningpackage',
            name='approximate_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cleaningpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-synced or fallback base price', max_digits=8),
        ),
        migrations.AlterField(
            model_name='cleaningpackage',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
