# Generated by Django 6.1 on 2026-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_cleaningpackage_balconies_cleaningpackage_bathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('living_areas', models.IntegerField(default=1)),
                ('balconies', models.IntegerField(default=0)),
                ('selected_addons', models.JSONField(blank=True, default=dict, help_text='Selected add-on details')),
                ('additional_notes', models.TextField(blank=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted / Called'), ('converted', 'Converted to Booking'), ('closed', 'Closed / Lost')], default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes regarding callback or follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Inquiry',
                'verbose_name_plural': 'Quote Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
